### ISSUE TITLE
Dropdown Navbar Menu on all pages

### ISSUE THREAD

**Issue by mjohnson518** [protocol/co2-storage#1]
Create a dropdown menu on all pages to declutter navbar and to easily traverse site.

Dropdown menu should should include links to:

- Home
- About
- Dashboard
- Templates
- Assets
- Docs & FAQ

**Comment by mjohnson518** [comment]
After some more thought, idk that we really need the dropdown menu. The navbar looks clean now without the 'Connect Wallet' on  Main. 

What do you think @adgsm?

**Comment by adgsm** [comment]
@mjohnson518 anyway it have to be done for handheld devices.

**Comment by mjohnson518** [comment]
Very true. Ok, I'll start working on it!

**Comment by mjohnson518** [comment]
Moving this back to To-Do since its been 2 months and I havent made any movement on it yet.

**Comment by adgsm** [comment]
Solved with eba8dbcbcf2ea7fba7b9c30027a068e5430759c8
