### ISSUE TITLE
Create JS API

### ISSUE THREAD

**Issue by adgsm** [protocol/co2-storage#11]

**Comment by mjohnson518** [comment]
Hyphen expressed how vitally important the API is for them to integrate. Once the API is available they'll start using CO2.Storage and uploading lots of data.

**Comment by adgsm** [comment]
JS-API created with the following commits
5aa3abd431032d78b776762e75eeca6f3eb2b85c
27a739a97061cf7f9c40d636181e6f80c3dda2c7
f81f0923a96f83c43d8d2fae2df8e566c3fc811e
