### ISSUE TITLE
Latest version (1.3.0) has warnings and errors

### ISSUE THREAD

**Issue by clay-centigrade** [protocol/co2-storage#110]
Given the cli command wrapper...

```javascript
program
    .command("add-template", "create a new template")
    .option('--schema <name>', program.STRING)
    .option('--name <name>', program.STRING)
    .option('--baseTitle <name>', program.STRING)
    .option('--baseReference <id>', program.STRING)
    .option('--description <describe>', program.STRING)
    .option('--parent <id>', program.STRING)
    .option('--chain <name>', program.STRING)
    .option('--outfile <name>', program.STRING)
    .action((args, options, logger) => {

        const eppTemplateName = "Graphene IWA Template "+options.name;

        loadJson(options.schema).then((schema) => {
            console.log("schema", schema);
            const templateBase = {title: options.baseTitle, reference: options.baseReference}
            addTemplate(schema[options.name].struct.fields, eppTemplateName, templateBase, options.description, options.parent, options.chain).then((r) => {
                console.log("Template", r);
                if (options.outfile && options.outfile.length > 0) {
                    console.log("Saving output to file", options.outfile);
                    saveOutput(options.outfile, r);
                }
            });
        });
    });
```
run with...

```bash
node --trace-warnings src/index.js add-template \
    --schema=$ADDRESS_INFO_SCHEMA \
    --name="AddressInfo" \
    --baseTitle="VCS" \
    --baseReference="bafyreigenzubua7r7rlxomgpyy2o4q46u6anvw3qvbxmlxhifkbrdbhcwm" \
    --description="IWA Address Info" \
    --parent="bafyreigijwcxu4nda2nol5x3cepjhel6mlvgyiizvivki3dpg3ttegdl2y" \
    --chain="rapaygo examples" \
    --outfile=$ADDRESS_INFO_TEMPLATE
```    
The co2-storage library emits the following warnings:
   
 ```
 (node:2681927) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
    at emitExperimentalWarning (node:internal/util:226:11)
    at fetch (node:internal/process/pre_execution:213:5)
    at fetch (/home/clay/data/github.com/centigrade-earth/co2-storage-spike/node_modules/ipfs-utils/src/http/fetch.node.js:24:3)
    at Client.fetch (/home/clay/data/github.com/centigrade-earth/co2-storage-spike/node_modules/ipfs-utils/src/http.js:141:7)
    at Client.fetch (file:///home/clay/data/github.com/centigrade-earth/co2-storage-spike/node_modules/ipfs-http-client/src/lib/core.js:205:20)
    at Client.post (/home/clay/data/github.com/centigrade-earth/co2-storage-spike/node_modules/ipfs-utils/src/http.js:188:17)
    at Object.getAll (file:///home/clay/data/github.com/centigrade-earth/co2-storage-spike/node_modules/ipfs-http-client/src/config/get-all.js:14:27)
    at FGStorage.startIpfs (file:///home/clay/data/github.com/centigrade-earth/co2-storage-spike/node_modules/@co2-storage/js-api/src/js/storage/FGStorage.js:128:41)
    at async FGStorage.ensureIpfsIsRunning (file:///home/clay/data/github.com/centigrade-earth/co2-storage-spike/node_modules/@co2-storage/js-api/src/js/storage/FGStorage.js:303:16)
    at async FGStorage.addTemplate (file:///home/clay/data/github.com/centigrade-earth/co2-storage-spike/node_modules/@co2-storage/js-api/src/js/storage/FGStorage.js:606:4)
    at async addTemplate (file:///home/clay/data/github.com/centigrade-earth/co2-storage-spike/src/co2s.js:86:29)
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'
  ```

**Comment by adgsm** [comment]
Hi @clay-centigrade 
I saw you've sent me the following via email as well.

> I am getting an error when trying to call the 
> 
> this.fgApiToken = (await this.getApiToken(true)).result.data.token
> 
> of the method FGStorage module
> 
> async addTemplate(template, name, base, description, parent, chainName) {
> 
> {
>   result: null,
>   error: {
>     code: 500,
>     message: 'Error whilst requesting "privateKeyToAccount" method. InvalidPrivateKeyError: Invalid Private Key, Not a valid string or uint8Array'
>   }
> }
> 

Can you please make sure you're storing your private key in the `.env` file with leading `0x...` and let me know did this solve all problems?

**Comment by adgsm** [comment]
Can you also make sure you're using correct FG_TOKEN in your `.env` file

**Comment by clay-centigrade** [comment]
ESTUARY_API_KEY=EST31da622.....-b68afd90a2faARY
INFURA_API_KEY=f1ce311d.....8dcbe229b931
PK=ed3be3f239a15d422142b5e67ce.....7646b2ecf31395355
FG_TOKEN=0170a873-54f5-.....4f21bd47e
METAMASK_ACCOUNT=0x3C0.....F0e1FDfC530624C99C80EDC
METAMASK_PK=ed3be3f239a15d42.....d23484274c9a37646b2ecf31

**Comment by clay-centigrade** [comment]
I also verify that these are available via...

const verifyEnv = (env) => {
// const env = process.env;
if (!env.ESTUARY_API_KEY) {
console.log("ESTUARY_API_KEY not set");
process.exit(1);
}
if (!env.INFURA_API_KEY) {
console.log("INFURA_API_KEY not set");
process.exit(1);
}
if (!env.PK) {
console.log("PK not set");
process.exit(1);
}
if (!env.FG_TOKEN) {
console.log("FG_TOKEN not set");
process.exit(1);
}
if (!env.METAMASK_ACCOUNT) {
console.log("METAMASK_ACCOUNT not set");
process.exit(1);
}
if (!env.METAMASK_PK) {
console.log("METAMASK_PK not set");
process.exit(1);
}
};

**Comment by clay-centigrade** [comment]
changing to this fixed it...

ESTUARY_API_KEY=EST31da622.....-b68afd90a2faARY
INFURA_API_KEY=f1ce311d.....8dcbe229b931
PK=0xed3be3f239a15d422142b5e67ce.....7646b2ecf31395355
FG_TOKEN=0170a873-54f5-.....4f21bd47e
METAMASK_ACCOUNT=0x3C0.....F0e1FDfC530624C99C80EDC
METAMASK_PK=ed3be3f239a15d42.....d23484274c9a37646b2ecf31

**Comment by adgsm** [comment]
I am not sure what are `METAMASK_ACCOUNT` and `METAMASK_PK` used for but please make sure that you have `PK` key prefixed with `0x`

**Comment by adgsm** [comment]
Right! We typed comments at the same time. I am glad you solved it :)

**Comment by clay-centigrade** [comment]
would love to be able to talk to you on slack... did you get the invite? or
the old discord.

**Comment by clay-centigrade** [comment]
Closing issue but maybe should be "Better error messages?" :)
