### ISSUE TITLE
Add separator for nested schemas

### ISSUE THREAD

**Issue by redransil** [protocol/co2-storage#113]
When you add multiple copies of a schema to a template, [example here](https://form.co2.storage/bafyreihg3pattrrdwvwtmh4653ea355kxioetygpqhjiqtd75xnqlb4dai) (click "+" a few times) it's hard to scroll through and see where the separations are from one schema to the next.

For UX, add a horizontal line separating them.

Example of what this could look like in the co2.storage preview:
![Screenshot 2023-08-18 at 3 40 45 PM](https://github.com/protocol/co2-storage/assets/39382262/d85b0b51-c966-4315-abc5-f541ff7fc072)

Example as a form:

![Screenshot 2023-08-18 at 3 42 21 PM](https://github.com/protocol/co2-storage/assets/39382262/545a28ae-ef29-4a43-a3f7-f618572f3ed5)

**Comment by adgsm** [comment]
Solved with commit 6a65f44
