### ISSUE TITLE
Add support for placeholder text to template creation page

### ISSUE THREAD

**Issue by mjohnson518** [protocol/co2-storage#70]
It would be very helpful to add support for placeholder text to the CO2.Storage template creation page. Screenshot below for reference.

<img width="641" alt="Screen Shot 2022-12-16 at 10 05 19" src="https://user-images.githubusercontent.com/44822571/208127370-0b1f03fb-a405-4880-94d1-060b64f09b50.png">

**Comment by adgsm** [comment]
Added to field types: string, text, date, dates, datetime, datetimes, daterange and datetimerange
Solved with commit 74f161a4e9268743be1ce84e6e37ca0e228e1724
