### ISSUE TITLE
Calculate amount of stored data per account and in total

### ISSUE THREAD

**Issue by adgsm** [protocol/co2-storage#72]

**Comment by redransil** [comment]
Two places where we should be able to see amounts stored:

- On the user account page (when you click the green button on the upper right) see a list of assets and their sizes; include link to that asset and list the indexing chain
- Total amount of data stored, across co2.storage, on the landing page

**Comment by adgsm** [comment]
Solved with 2504adb7fd51fc0b20a08066b7bc3c7f75efb8d1
