### ISSUE TITLE
Asset links not loading

### ISSUE THREAD

**Issue by redransil** [protocol/co2-storage#75]
When I click on the CID of an asset, it links to explore.ipld.io and won't load. 

Example - clicking here:
[screenshot](https://user-images.githubusercontent.com/39382262/215601405-e0da86a6-22cb-4ab1-ba42-d39399848ce1.png)

links to: https://explore.ipld.io/#/explore/bafyreifegsrfciz3vwrrjldmz457dnxe4mfpkvyucwokbkmkxw74cxs66u

and for me, it doesn't load

**Comment by redransil** [comment]
Also going to a gateway like https://green.filecoin.space/ipfs/bafyreiexbkck5ek7dqsrqt6zo2b57abocr7rmifu5qtk4wlch7q4gvq3oq

leads to:

> ipfs cat /ipfs/bafyreiexbkck5ek7dqsrqt6zo2b57abocr7rmifu5qtk4wlch7q4gvq3oq: unknown node type

**Comment by redransil** [comment]
Same for:
https://green.filecoin.space/ipfs/bafyreifegsrfciz3vwrrjldmz457dnxe4mfpkvyucwokbkmkxw74cxs66u

> ipfs cat /ipfs/bafyreifegsrfciz3vwrrjldmz457dnxe4mfpkvyucwokbkmkxw74cxs66u: unknown node type

**Comment by adgsm** [comment]
bafyreiexbkck5ek7dqsrqt6zo2b57abocr7rmifu5qtk4wlch7q4gvq3oq
and 
bafyreifegsrfciz3vwrrjldmz457dnxe4mfpkvyucwokbkmkxw74cxs66u
are DAG structures, try using following with your CLI
`ipfs dag get bafyreifegsrfciz3vwrrjldmz457dnxe4mfpkvyucwokbkmkxw74cxs66u`

the result should be something like following
`{"cid":"bafyreiexbkck5ek7dqsrqt6zo2b57abocr7rmifu5qtk4wlch7q4gvq3oq","creator":"0x4d2f165969e5bddc21c31a04626c2acd1283685f","description":"","name":"noaa-goes16 / ABI-L1b-RadC / 2000 / 001 / 12 (0,1 & 2)","parent":null,"template":"bafyreidfm66giw7w3eeylvqpzx7pkopgd57xv4mumbjzcy4juajr5unkqa","timestamp":"2023-01-30T15:28:07.043Z","version":"1.0.0"}`

**Comment by adgsm** [comment]
[https://explore.ipld.io/#/explore/bafyreifegsrfciz3vwrrjldmz457dnxe4mfpkvyucwokbkmkxw74cxs66u](https://explore.ipld.io/#/explore/bafyreifegsrfciz3vwrrjldmz457dnxe4mfpkvyucwokbkmkxw74cxs66u) loads for me but this indeed needs improvement.

**Comment by adgsm** [comment]
Added following nodes to bootstrap
`'/dns4/node0.preload.ipfs.io/tcp/443/wss/p2p/QmZMxNdpMkewiVZLMRxaNxUeZpDUb34pWjZ1kZvsd16Zic',
  '/dns4/node1.preload.ipfs.io/tcp/443/wss/p2p/Qmbut9Ywz9YEDrz8ySBSgWyJk41Uvm2QJPhwDJzJyGFsD6',
  '/dns4/node2.preload.ipfs.io/tcp/443/wss/p2p/QmV7gnbW5VTcJ3oyM2Xk1rdFBJ3kTkvxc87UFGsun29STS',
  '/dns4/node3.preload.ipfs.io/tcp/443/wss/p2p/QmY7JB6MQXhxHvq7dBDh4HpbH29v4yE9JRadAVpndvzySN'`
