### ISSUE TITLE
Asset Data Fields Unordered

### ISSUE THREAD

**Issue by mjohnson518** [protocol/co2-storage#76]
I'm testing out adding some Audit Outputs to CO2.Storage and wanted to flag a bug I'm experiencing.
I created a Template based on the [SP_elec_audit_data_V1.0.0](https://drive.google.com/file/d/1G7UQ7sVrtcfiTKWb5ezqfCJ7CG5JPUhL/view?usp=sharing) schema. But once I go and use that Template to create an Asset, the data fields are not in the right order. 

This needs to be addressed to ensure the data fields remain in the correct order once the Template has been created. Screenshots added below for reference:

<img width="1401" alt="Screen Shot 2023-02-13 at 17 38 22" src="https://user-images.githubusercontent.com/44822571/218534755-fc5b0899-49e3-4db0-88b3-b3748cd9952a.png">

<img width="757" alt="Screen Shot 2023-02-13 at 17 53 22" src="https://user-images.githubusercontent.com/44822571/218534993-d4d12af9-3556-40e4-8144-de0462e69e6d.png">

Can we address this?

**Comment by adgsm** [comment]
Solved with 4e71cc2
by adding a possibility to create a template with ordered lists structures.
[Example 1](https://web2.co2.storage/templates/bafyreid43f2jb3xbyrrwko44kg3dnuqkxmwnhdtqsr7aoi3h3soamtkcyy), list of objects
[Example2](https://web1.co2.storage/templates/bafyreidsczvmq4667cae7t6ib6stkiw4vkssqzimwe6fex56jotvltsldi), list of arrays
