### ISSUE TITLE
"SP Audits" environment

### ISSUE THREAD

**Issue by mjohnson518** [protocol/co2-storage#77]
Just as we have a "Sandbox" environment, can we also create an "SP Audits" environment for Auditors to begin uploading audit outputs?

**Comment by adgsm** [comment]
Yes, this is possible. Simply click + sign next to environment name and type in a name of the environment (e.g. "fil-mainnet-archive") and then hit Enter, 
or
add `?chain_name=<your-environment-name>` to the address bar.

**Comment by mjohnson518** [comment]
Closing bc functionality already exists :man-facepalming:

**Comment by mjohnson518** [comment]
Reopening because others can not see when I create a template/asset in a new environment, and when I refresh the new environment is gone. 

Any idea why this happens?

**Comment by adgsm** [comment]
https://user-images.githubusercontent.com/5786211/219559794-388678c3-aecb-4c79-b02d-269d4590c1ee.mov

**Comment by mjohnson518** [comment]
Thanks, Moca. Not sure why the environment wasn't staying when I refreshed yesterday, but looks fine now
