### ISSUE TITLE
How do I get the private key for authentication

### ISSUE THREAD

**Issue by mendsalbert** [protocol/co2-storage#80]

**Comment by mendsalbert** [comment]
@jbenet @adgsm @redransil @mjohnson518

**Comment by adgsm** [comment]
[https://filecoin-green.gitbook.io/filecoin-green-documentation/co2.storage-docs/setting-up-the-cli](https://filecoin-green.gitbook.io/filecoin-green-documentation/co2.storage-docs/setting-up-the-cli)
