### ISSUE TITLE
Modify message signatures to implement Provenance Protocol

### ISSUE THREAD

**Issue by redransil** [protocol/co2-storage#84]
Modify message signature generated when the user signs a message to match the [Provenance Data Model](https://docs.google.com/presentation/d/1MqlHzJfDEdOZhRMngxDOzkGLwQnewNnohG1HWX3LAjY/edit?usp=sharing). This will require:

- Adding a field for "contributor name" which the account owner can fill in. Likely add this to the page with the API and Estuary keys. Defaults to null.
- Add a data license field to that same account page. Should be a drop-down with options "CC0 (No Rights Reserved, Public Domain)", "CC-BY (Attribution)", "CC BY-SA (Attribution-ShareAlike)", "CC BY-NC (Attribution-NonCommercial)", "Reserved" and be set on the same page as contributor name. Defaults to null
- Modify the data structure produced by signing a message to match the structure below.
- The "Indexing Chain" is the data structure chosen in the upper left hand corner of the CO2.storage UI (ie "sandbox")
- Store that data structure as an asset in CO2.Storage on the same indexing chain.
- In the UI where the signature is verified in a popup, add a link to the provenance message CID

{
   “protocol” : “provenance protocol”,
   “version” : “1.0.0”,
   “data_license” : _from account_,
   “provenance_community”: _name of indexing chain_,
   “contributor_name” : _from form_,
   “method” : “eth_signTypedData_v4”,
   “verifying_contract” : “0x7c75AA9001c4…”,
   “chain_id” : “0x1”,
   “contributor_key” : _key of message signer_,     
   “payload” : _CID of Data / Type / Asset_,
   “signature” : _sign CID of Message A_,
   “notes”: null
}

<img width="991" alt="Screenshot 2023-04-26 at 7 50 46 AM" src="https://user-images.githubusercontent.com/39382262/234614547-cd66f960-7176-47a8-9b47-57607146bd20.png">

**Comment by adgsm** [comment]
> Add a data license field to that same account page. Should be a drop-down with options "CC0 (No Rights Reserved, Public Domain)", "CC-BY (Attribution)", "CC BY-SA (Attribution-ShareAlike)", "CC BY-NC (Attribution-NonCommercial)", "Reserved" and be set on the same page as contributor name. Defaults to null

Q: As per the request, the data license is related to account / wallet and all its contained types / assets, right? It would be a bit more flexible if we set data license related only to a specific type / asset?

**Comment by adgsm** [comment]
> The "Indexing Chain" is the data structure chosen in the upper left hand corner of the CO2.storage UI (ie "sandbox")

Q: Is the indexing chain supposed to be stored in Provenance message. I can't see it defined here?
`{
“protocol” : “provenance protocol”,
“version” : “1.0.0”,
“data_license” : ,
“provenance_community”: ,
“contributor_name” : ,
“method” : “eth_signTypedData_v4”,
“verifying_contract” : “0x7c75AA9001c4…”,
“chain_id” : “0x1”,
“contributor_key” : ,
“payload” : <CID of Data / Type / Asset>,
“signature” : ,
“notes”: null
}`

**Comment by redransil** [comment]
> > Add a data license field to that same account page. Should be a drop-down with options "CC0 (No Rights Reserved, Public Domain)", "CC-BY (Attribution)", "CC BY-SA (Attribution-ShareAlike)", "CC BY-NC (Attribution-NonCommercial)", "Reserved" and be set on the same page as contributor name. Defaults to null
> 
> 
> 
> Q: As per the request, the data license is related to account / wallet and all its contained types / assets, right? It would be a bit more flexible if we set data license related only to a specific type / asset?
> 
> 
> 
> 

You’re right, probably the drop-down should appear when they are generating the signature message?

**Comment by redransil** [comment]
> > The "Indexing Chain" is the data structure chosen in the upper left hand corner of the CO2.storage UI (ie "sandbox")
> 
> 
> 
> Q: Is the indexing chain supposed to be stored in Provenance message. I can't see it defined here?
> 
> `{
> 
> “protocol” : “provenance protocol”,
> 
> “version” : “1.0.0”,
> 
> “data_license” : ,
> 
> “provenance_community”: ,
> 
> “contributor_name” : ,
> 
> “method” : “eth_signTypedData_v4”,
> 
> “verifying_contract” : “0x7c75AA9001c4…”,
> 
> “chain_id” : “0x1”,
> 
> “contributor_key” : ,
> 
> “payload” : <CID of Data / Type / Asset>,
> 
> “signature” : ,
> 
> “notes”: null
> 
> }`

Fixed above; it's in the ** “provenance_community”** field

**Comment by adgsm** [comment]
I believe it would be beneficial to add a timestamp as well to the Provenance message, so it would look like as following.
`{
“protocol” : “provenance protocol”,
“version” : “1.0.0”,
“data_license” : ,
“provenance_community”: ,
“contributor_name” : ,
“method” : “eth_signTypedData_v4”,
“verifying_contract” : “0x7c75AA9001c4…”,
“chain_id” : “0x1”,
“contributor_key” : ,
“payload” : <CID of Data / Type / Asset>,
“signature” : ,
“notes”: null,
“timestamp” : “2023-05-02T08:02:19.904Z”
}`

**Comment by adgsm** [comment]
@redransil Who is allowed to sign records?

**Comment by adgsm** [comment]
@redransil Provenance protocol implemented in full scope.
Commits:
8c13f64a1c8ab692c5017defa00ac7dffe8060a0
9e1221f999edf59b47ad8109ba6d15ec4d041785
d8be8dd050642eee475eb089263e68e6d483c0d6
a96784e0236d938df1c0bf191dffd7f570e7ac7e
2ea22ee47d7913cbed1199485b5af91533bc31d1
f1a9679368207fbce87a0bf5a99cc8e6b177afb7
b1f74d456bcaa5ec9608fb677515b8022afc2417

**Comment by adgsm** [comment]
Request is change. Provenance message needs to be split in two messages as following.

> Message B:
{
     “protocol” : “provenance protocol”,
   “version” : “1.0.0”,
    "provenance_message" : <CID of Message A>,
    “signature” : <sign CID of Message A>,
    “contributor_key” : <key of message signer>,
    “method” : “eth_signTypedData_v4”,
   “verifying_contract” : “0x7c75AA9001c4…”,
   “chain_id” : “0x1”
}
Message A:
{
   “protocol” : “provenance protocol”,
   “version” : “1.0.0”,
   “data_license” : <from account>,
   “provenance_community”: <name of indexing chain>,
   “contributor_name” : <from form>,
   “contributor_key” : <key of message signer>,
   “payload” : <CID of Data / Type / Asset>,
    “notes”: null
}

**Comment by adgsm** [comment]
Solved with
f62097c0d085e81a16126a84cce3da1a03fdc564
e5d48b10057b557ab3c956d824adefd4f2d11c35
