### ISSUE TITLE
CO2.storage Form v1

### ISSUE THREAD

**Issue by redransil** [protocol/co2-storage#86]
[UI Example](https://www.figma.com/file/lqir54wHilvEZPaV8AIWK1/CO2.Storage-Form?type=design&node-id=0%3A1&t=Lr7CXlu31HX4xUTP-1)
We need an easy way for people to create an asset, without having to understand the details of co2.storage. This should do the following:

- Introduce a URL form.co2.storage/<CID> where <CID> is a Template (ie: [bafyreidavm5scus7dg75e2iu3ki5xc6onrbnrjyv4f7josvln2uwmo7p3u](https://explore.ipld.io/#/explore/bafyreidavm5scus7dg75e2iu3ki5xc6onrbnrjyv4f7josvln2uwmo7p3u))
- It should produce a form that looks something like the [v1 UI Example](https://www.figma.com/file/lqir54wHilvEZPaV8AIWK1/CO2.Storage-Form?type=design&node-id=0%3A1&t=Lr7CXlu31HX4xUTP-1)
- The fields displayed should be only the fields in the data schema. In the bafyreidav... example, the fields are [here](https://explore.ipld.io/#/explore/bafyreihxmr3djalvov5wbwyyk2jjswvbvirkmfhea5p6bynr7h7z7fqokm)
- The user can log in with their metamask account

Once the user fills out the form and hit submit, this does three things:
1. It creates an asset in CO2.storage with the template specified in the URL. This should belong to the same indexing chain as the template.
2. It should create a provenance protocol record attesting to the information in the asset
3. It should link to a thank-you page that has two options: (1) link to the asset, (2) submit a new response

**Comment by redransil** [comment]
Can the form page have a white background?

We can add more customization and UX options in a later version of this

**Comment by adgsm** [comment]
> It should create a provenance protocol record attesting to the information in the asset

Does this mean it should popup user for the Contributor name and the data license before creating the asset?

**Comment by redransil** [comment]
Add a section for Data Provenance Information
Contributor (Your) Name: (String)
Data License: (Dropdown)

**Comment by redransil** [comment]
Dealing with asset metadata:

- Allow a hide option in the URL
- If hidden, auto-generate title and leave description blank
- If not hidden, add an asset metadata section at the bottom of the form

**Comment by adgsm** [comment]
- Forms are deployed at https://form.co2.storage/
- An example how to access one of your latest nested forms is the following https://form.co2.storage/bafyreidxkzi56ecxil3vtmjwlxilrh7xfa2qukhvmfcokdqlleyjus6o5a
- You can hide provenance and metadata sections by providing following parameters in a query: ?metadata=false&provenance=false eg https://form.co2.storage/bafyreidxkzi56ecxil3vtmjwlxilrh7xfa2qukhvmfcokdqlleyjus6o5a?metadata=false&provenance=false
- Once asset is created and signed Thank you information is shown together with an created asset and provenance info listed below, like following: https://form.co2.storage/asset/bafyreie5oviq5dfmr3pb4q5wkj5p2n2j55uixfzrftuux4fum25md4qqjq?thank-you=true
- From there you can either create a new asset or examine existing one and its provenance info. Creating another one will always lead back to the template form with parameters you have initially set when you have created asset, so if you have set ?metadata=false&provenance=false then those parameters will remain for creating new asset (but you can change/alter it if needed).
- Besides the asset cid/link there is a copy icon next to it so you can copy the cid of an created asset.
- Provenance info (contributor name and data license) once provided are persisted in a session and a cookie.
- In general you can use form domain with added /asset (e.g. https://form.co2.storage/asset) to see any asset existing in co2.storage, even if it is not created within the form. For example https://form.co2.storage/asset/bafyreihxusepavuxhwfzhl334oxdgzucbj3bwad5jivuxnv2clhzzqkok4.
- A separate domain name that we can use for this as well is https://asset.co2.storage/bafyreihxusepavuxhwfzhl334oxdgzucbj3bwad5jivuxnv2clhzzqkok4

**Comment by adgsm** [comment]
Preview asset should have read-only fields

**Comment by adgsm** [comment]
Solved with
e372a6ae27377682115f30f88598c291ac3be272
a934aa436ff32978039e0a81f1c1bfdb215c5a3d
138529eded4521a567975aac321c922641ad640d
