### ISSUE TITLE
Asset Signature 

### ISSUE THREAD

**Issue by mjohnson518** [protocol/co2-storage#87]
There seems to be a problem signing Assets. The auditors said that when they click on the gray sign icon on the Dashboard, the browser spins but nothing else happens.

I'll follow up on this issue with screenshots and additional info as its provided by the auditors.

**Comment by adgsm** [comment]
Can you share what you see in the console log?
Do they have Metamask extension installed?

**Comment by mjohnson518** [comment]
![signing](https://github.com/protocol/co2-storage/assets/44822571/e50e785e-8e2b-4b44-b419-c20d7b1f4b98)


Auditors still can't sign assets. They confirmed that they are the creator of it, and they have MM installed and visible. After clicking the sign icon, they see a message 'Loading....', and then it goes back to the Dashboard

**Comment by adgsm** [comment]
> ![signing](https://user-images.githubusercontent.com/44822571/237898197-e50e785e-8e2b-4b44-b419-c20d7b1f4b98.png)
> 
> Auditors still can't sign assets. They confirmed that they are the creator of it, and they have MM installed and visible. After clicking the sign icon, they see a message 'Loading....', and then it goes back to the Dashboard

Can they share this screen but right after they clicked sign button and spinner started spinning?

**Comment by mjohnson518** [comment]
![signing console log](https://github.com/protocol/co2-storage/assets/44822571/0d4bf9b9-9521-4c7b-95f6-9042b57624b2)

Screenshot from one of the auditors

**Comment by adgsm** [comment]
> ![signing console log](https://user-images.githubusercontent.com/44822571/237903051-0d4bf9b9-9521-4c7b-95f6-9042b57624b2.png)
> 
> Screenshot from one of the auditors

![image](https://github.com/protocol/co2-storage/assets/5786211/086a0c4e-6680-4c1d-bdac-e654fce246fe)
This part (ipfs node trying to dial itself is irrelevant and not a problem here)

The remaining part of logs seems to come from somewhere else / some older version.

Please do the hard refresh.

Also, I guess you have Metamask window hidden after starting the signing process. Can you open Metamask window right after you start signing process and when you see spinner spinning?

**Comment by adgsm** [comment]
Please do share what is happening **when/after you start signing process**.

**Comment by mjohnson518** [comment]
Resolved. TY @adgsm
