### ISSUE TITLE
Viewer that doesn't require login

### ISSUE THREAD

**Issue by redransil** [protocol/co2-storage#95]
Move the functionality that is currently at `form.co2.storage/asset` and move it to `asset.co2.storage`

Make viewing an asset at this address not require a login

**Comment by adgsm** [comment]
From @redransil 

> When I load https://asset.co2.storage/bafyreicwenqaomayjolfcd6ag6pbrsl7x6p63rqjpzb5u3gycnvo2hs3vm with no metamask, a few things:
It gives an error message “No valid web3 provider is found” Can we remove this? Accessing the asset with no wallet should be a legitimate way to view it (ie no error)
It says “There is no provenance information available for this record yet.” Can we make it display the provenance information, but say “not verified. Connect your wallet to verify”
When provenance information is verified, can we add a badge that shows it was verified in your browser
Can we add a “connect wallet” button

**Comment by adgsm** [comment]
Solved with ed150183d38989d44f1186710fb1efb437d48a75
Initial logic implemented with e2e3a30705695f31842973d701f6d4d00e489257
