### ISSUE TITLE
Number of login messages

### ISSUE THREAD

**Issue by redransil** [protocol/co2-storage#97]
When I log in to co2.storage with metamask, I have to sign three messages (See top of images, "1 of 3 requests waiting to be acknowledged"). Is this a bug? Can we reduce this to one message instead of three? 

<img width="353" alt="Screenshot 2023-05-25 at 2 45 02 PM" src="https://github.com/protocol/co2-storage/assets/39382262/e265abe9-3c5a-4272-b28d-2a5934053843">

**Comment by adgsm** [comment]
Solved with 4bf48f53ef27f8d073245dd0a0b4830bb725cd65
